name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        python-version: ["3.7.1", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
      - name: Build package
        run: python -m build
      - name: Install package
        run: pip install dist/autoexif-*.whl
      - name: Test package
        run: |
          autoexif --help  # Basic test to ensure CLI works
        shell: bash

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
